include:
  - remote: 'https://gitlab.com/syseleven/gitlab-ci-templates/raw/3.12.1/DockerBuild-kaniko.yml'
  - remote: 'https://gitlab.com/syseleven/gitlab-ci-templates/raw/3.12.1/ContainerImageCVEScan.yml'

cache:
  paths:
    - node_modules/
    - .cache/
    - public/

pages:
  image: node:latest
  script:
    - npm install
    - ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  only:
    - main
